### ISSUE TITLE
Bot gives wrong channel permission to user.

### ISSUE THREAD

**Issue by WillDxx** [BestMordaEver/Voice-Manager#11]
As stated in documentation lobby with moderate permission should give users
Move Members permission but it gives them Manage Permission role which is potentialy hazardus.
For example in my case user could change his room to public, change @everyone ping permission and ping everyone on server.

Source:
https://github.com/BestMordaEver/Voice-Manager/wiki/Setup-Guide#host-permissions
moderate - same as mute, plus gives host Move Members permission in their room

**Comment by BestMordaEver** [comment]
This is an undocumented special case - bot will give **Manage Permissions** only if bot has administrator privileges. Right now there's no demand to further granularize permission settings, unless you specifically need that to be a separate permission.

**Comment by BestMordaEver** [comment]
I've added the clause in the documentation, feel free to reopen the issue if you need bot to handle your case differently.
