### ISSUE TITLE
initDB.lua missing 2 columns in both self host release and master + wrong constraint

### ISSUE THREAD

**Issue by magssibbert** [BestMordaEver/Voice-Manager#12]
I was tryin to get a self host to work, and it always errored out, I managed to figuere out the reason: the columns for role and permission in table guilds were missing (in both the provided DBs and the initDB.lua). This issue was persistent in both versions i worked with, the newest release v4.3.0 and the current version in the master branch.
![Screenshot 2022-12-31 121910](https://user-images.githubusercontent.com/45903063/210134775-e719197b-b3aa-41f5-9863-de775550b2ab.png)

Additionally after adding those 2, there was an issue regarding the NOT NULL constraint for the column cLimit, resulting in the guild not being properly safed. I removed that aswell.
![Screenshot 2022-12-31 122337](https://user-images.githubusercontent.com/45903063/210134929-6db7cbb3-d9d8-40c8-b543-6daf5dfccd9d.png)

Here my fixed paragraph:

```lua
CREATE TABLE guilds(
	id VARCHAR PRIMARY KEY,
	cLimit INTEGER,		/* mutable, default 500 */
	role VARCHAR,
	permissions INTEGER NOT NULL
)]])
```

I am not 100% sure if this is perfect fix but sofar the Bot has been running without error.

PS: The Self Host guide could be improved a bit by adding tips on how to get the correct of libsqlite3, as that wasnt intuitive for me as an amateur(and didnt help in isolationg the issue).

**Comment by BestMordaEver** [comment]
Fixed in b28588e
