### ISSUE TITLE
Voice Channel's created always comes out as "no game"

### ISSUE THREAD

**Issue by theCrius** [BestMordaEver/Voice-Manager#8]
Hey there, sorry to report this but since a couple days (when i started get reports from my users) the channels generated with template `%game%` don't seems to work properly.

I tested myself and have had Game Activity visible but the channel kept coming out as "no game".

I tried to edit the template with `%game% %counter` to see if it was an issue with the templating itself but the counter seems to come out fine. Only the `%game%` part seems broken right now.

**Comment by theCrius** [comment]
It has been 21 days since this issue was created. I understand it was due to a change in the discord API? Is there any ETA for this to be resolved?

**Comment by BestMordaEver** [comment]
@theCrius normally it should take somewhere between 2-4 weeks, but for some reason they had to pass the case to their devs, so this may take longer. They didn't give me an ETA, I poked them about that, will post updates as they come.

**Comment by theCrius** [comment]
Thanks @BestMordaEver.

**Comment by BestMordaEver** [comment]
@theCrius bot got the intent whitelist, issue is fixed now
